### ISSUE TITLE
Missing C# statement?

### ISSUE THREAD

**Issue by Noctis-** [ardalis/OrganizingAspNetCore#12]
https://github.com/ardalis/OrganizingAspNetCore/blob/f15f2cf07fde606e3037c1f9642963a267e89145/WithRazorPages/Startup.cs#L118

this will output an error on the next line (logger.LogWarning...), but it seems something is missing in the line above it

**Comment by ardalis** [comment]
Thanks! Sorry, that was an errant merge.
