### ISSUE TITLE
The add method of the DbRepository is slow

### ISSUE THREAD

**Issue by ivaylokenov** [ardalis/OrganizingAspNetCore#2]
It should not take the whole table.

**Comment by ardalis** [comment]
Yeah, that's definitely demo code. In a real application you'd just have IDENTITY set on the ID column and you wouldn't need most of the code in Add().

**Comment by ivaylokenov** [comment]
Fair enough. I just hope noone will copy it in their source.

**Comment by ardalis** [comment]
This is fixed now, btw.
