### ISSUE TITLE
Two controllers with the same name?

### ISSUE THREAD

**Issue by dotnetshadow** [ardalis/OrganizingAspNetCore#4]
Hi I'm currently having an issue with routing using features folders,
I have two routes with the same controller name but in different folders

- ADMIN
    - FOO
    - Feature 2
    - Feature 3
- FOO

```
namespace MyProject.Features.Admin
{
    [Route("/Admin/Foo/")]
    public class BarController : Controller {
        [Route("/Index/")]
        public async Task<IActionResult> Index()
        {

        }
    }
}    


namespace MyProject.Features.Feature1
{
    [Route("/Bar/")]
    public class BarController : Controller {
        [Route("/Index/")]
        public async Task<IActionResult> Index()
        {

        }
    }
}    
```

But when I want to go to the non admin version in razor:
```<a asp-area="" asp-controller="Bar" asp-action="Index" ...```

It seems to only default to the Admin one, mainly because maybe there isn't a check for namespace?

**Comment by ardalis** [comment]
This sounds like a bug. I'll try and get it fixed. Sorry, I didn't see any notification this issue had been opened until just now.

**Comment by ardalis** [comment]
I suspect as a workaround you can use a named route and asp-route in your link.

    <a asp-route="NinjaSwords">Ninja Swords List</a>

    [Route("/Ninjas/Swords/", Name ="NinjaSwords")]
    public class SwordsController : Controller
