### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by chrismatheson** [ardalis/OrganizingAspNetCore#7]
Just wanted to say thanks for a great project outline.

Ive stolen the `WithFeatureFolders` project as my base, i really don't like the standard separation layout and this was exactly what i wanted (but don't yet have the ability to set it up myself) 

So thanks again!

C

**Comment by ardalis** [comment]
Awesome, thanks for sharing. Check out my CleanArchitecture starter, too, if you're looking to build ASP.NET Core apps.

https://github.com/ardalis/cleanarchitecture
